/*
 * Copyright (C) 2012  Krawler Information Systems Pvt Ltd
 * All rights reserved.
 * 
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License
 * as published by the Free Software Foundation; either version 2
 * of the License, or (at your option) any later version.
 * 
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 * 
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
*/
package com.krawler.crm.database.tables; 
// Generated Jul 9, 2009 7:57:07 PM by Hibernate Tools 3.2.1.GA

import java.io.Serializable;
import java.util.Date;

/**
 * CrmAccount generated by hbm2java
 */
import com.krawler.common.admin.*;
import com.krawler.common.stats.StatUtil;
import java.util.HashSet;
import java.util.Set;
public class CrmAccount  implements java.io.Serializable {


     private String accountid;
     private User usersByUpdatedbyid;
     private DefaultMasterItem crmCombodataByAccounttypeid;
     private String accounttypeID;
     private String industryID;
     private User usersByCreatedbyid;
     private CrmLead crmLead;
     private Company company;
     private CrmProduct crmProduct;
     private DefaultMasterItem crmCombodataByIndustryid;
     private String accountname;
     private String phone;
     private String email;
     private String website;
     private String ownershipid;
     private String revenue;
     private Double revenuenum;
     private String marketshare;
     private String mailstreet;
     private String mailcity;
     private String mailstate;
     private String mailcountry;
     private String mailzip;
     private String shipstreet;
     private String shipcity;
     private String shipstate;
     private String shipcountry;
     private String shipzip;
     private String description;
     private String price;
     private Double pricenum;
     private Date updatedon;
     private Date createdon;
     private Long updatedOn;
     private Long createdOn;
     private boolean  isarchive;
     private int deleteflag;
     private int validflag;
     private String cellstyle;
     private Set<accountOwners> accountOwners = new HashSet();
     private Set crmProducts = new HashSet();
     private CrmAccountCustomData CrmAccountCustomDataobj;

    private String companyid;
     public String getCompanyid() {
        return companyid;
    }

    public void setCompanyid(String companyid) {
        this.companyid = companyid;
    }
    
    public CrmAccountCustomData getCrmAccountCustomDataobj() {
        return CrmAccountCustomDataobj;
    }

    public void setCrmAccountCustomDataobj(CrmAccountCustomData CrmAccountCustomDataobj) {
        this.CrmAccountCustomDataobj = CrmAccountCustomDataobj;
    }

    public CrmAccount() {
    }


    public String getAccountid() {
        return this.accountid;
    }

    public void setAccountid(String accountid) {
        this.accountid = accountid;
    }
    public User getUsersByUpdatedbyid() {
        return this.usersByUpdatedbyid;
    }

    public void setUsersByUpdatedbyid(User usersByUpdatedbyid) {
        this.usersByUpdatedbyid = usersByUpdatedbyid;
    }
    public DefaultMasterItem getCrmCombodataByAccounttypeid() {
        return this.crmCombodataByAccounttypeid;
    }

    public void setCrmCombodataByAccounttypeid(DefaultMasterItem crmCombodataByAccounttypeid) {
        this.crmCombodataByAccounttypeid = crmCombodataByAccounttypeid;
    }
    public User getUsersByCreatedbyid() {
        return this.usersByCreatedbyid;
    }

    public void setUsersByCreatedbyid(User usersByCreatedbyid) {
        this.usersByCreatedbyid = usersByCreatedbyid;
    }
    
    public CrmLead getCrmLead() {
        return this.crmLead;
    }

    public void setCrmLead(CrmLead crmLead) {
        this.crmLead = crmLead;
    }
    public Company getCompany() {
        return this.company;
    }

    public void setCompany(Company company) {
        this.company = company;
    }
    public CrmProduct getCrmProduct() {
        return this.crmProduct;
    }

    public void setCrmProduct(CrmProduct crmProduct) {
        this.crmProduct = crmProduct;
    }

    public DefaultMasterItem getCrmCombodataByIndustryid() {
        return crmCombodataByIndustryid;
    }

    public void setCrmCombodataByIndustryid(DefaultMasterItem crmCombodataByIndustryid) {
        this.crmCombodataByIndustryid = crmCombodataByIndustryid;
    }

    public String getAccounttypeID() {
        return accounttypeID;
    }

    public void setAccounttypeID(String accounttypeID) {
        this.accounttypeID = accounttypeID;
    }

    public String getIndustryID() {
        return industryID;
    }

    public void setIndustryID(String industryID) {
        this.industryID = industryID;
    }
    public String getAccountname() {
        return this.accountname;
    }

    public void setAccountname(String accountname) {
        this.accountname = accountname;
    }
    public String getPhone() {
        return this.phone;
    }

    public void setPhone(String phone) {
        this.phone = phone;
    }
    public String getEmail() {
        return this.email;
    }

    public void setEmail(String email) {
        this.email = email;
    }
    public String getWebsite() {
        return this.website;
    }

    public void setWebsite(String website) {
        this.website = website;
    }
    public String getOwnershipid() {
        return this.ownershipid;
    }

    public void setOwnershipid(String ownershipid) {
        this.ownershipid = ownershipid;
    }
    public String getRevenue() {
        return this.revenue;
    }

    public void setRevenue(String revenue) {
        this.revenue = revenue;
    }

    public Double getRevenuenum() {
        try {
            return Double.parseDouble(this.getRevenue());
        } catch(Exception ex) {
            return Double.parseDouble("0");
        }
    }

    public void setRevenuenum(Double revenuenum) {
        this.revenuenum = revenuenum;
    }
    
    public String getMarketshare() {
        return this.marketshare;
    }

    public void setMarketshare(String marketshare) {
        this.marketshare = marketshare;
    }
    public String getMailstreet() {
        return this.mailstreet;
    }

    public void setMailstreet(String mailstreet) {
        this.mailstreet = mailstreet;
    }
    public String getMailcity() {
        return this.mailcity;
    }

    public void setMailcity(String mailcity) {
        this.mailcity = mailcity;
    }
    public String getMailstate() {
        return this.mailstate;
    }

    public void setMailstate(String mailstate) {
        this.mailstate = mailstate;
    }
    public String getMailcountry() {
        return this.mailcountry;
    }

    public void setMailcountry(String mailcountry) {
        this.mailcountry = mailcountry;
    }
    public String getMailzip() {
        return this.mailzip;
    }

    public void setMailzip(String mailzip) {
        this.mailzip = mailzip;
    }
    public String getShipstreet() {
        return this.shipstreet;
    }

    public void setShipstreet(String shipstreet) {
        this.shipstreet = shipstreet;
    }
    public String getShipcity() {
        return this.shipcity;
    }

    public void setShipcity(String shipcity) {
        this.shipcity = shipcity;
    }
    public String getShipstate() {
        return this.shipstate;
    }

    public void setShipstate(String shipstate) {
        this.shipstate = shipstate;
    }
    public String getShipcountry() {
        return this.shipcountry;
    }

    public void setShipcountry(String shipcountry) {
        this.shipcountry = shipcountry;
    }
    public String getShipzip() {
        return this.shipzip;
    }

    public void setShipzip(String shipzip) {
        this.shipzip = shipzip;
    }
    public String getDescription() {
        return this.description;
    }

    public void setDescription(String description) {
        this.description = description;
    }
    public String getPrice() {
        return this.price;
    }

    public void setPrice(String price) {
        this.price = price;
    }

    public Double getPricenum() {
        try {
            return Double.parseDouble(this.getPrice());
        } catch(Exception ex) {
            return Double.parseDouble("0");
        }
    }
    public void setPricenum(Double pricenum) {
        this.pricenum = pricenum;
    }

    public Long getCreatedOn() {
        return createdOn;
    }

    public void setCreatedOn(Long createdOn) {
        this.createdOn = createdOn;
    }

    public Long getUpdatedOn() {
        return updatedOn;
    }

    public void setUpdatedOn(Long updatedOn) {
        this.updatedOn = updatedOn;
    }
    
    public Date getUpdatedon() {
        if(this.updatedOn!=null)
            return new Date(this.updatedOn);
        return null;
    }

    public void setUpdatedon(Date updatedon) {
        this.updatedOn = updatedon.getTime();
    }
    public Date getCreatedon() {
        if(this.createdOn!=null)
        createdon=new Date(this.createdOn);
        return createdon;
    }
    public String getCreatedonGMT() {
        return StatUtil.DATE_FORMAT_GMT.format(getCreatedon());
    }
    public void setCreatedon(Date createdon) {
        this.createdOn = createdon.getTime();
    }

    public boolean getIsarchive() {
        return this.isarchive;
    }

    public void setIsarchive(boolean isarchive) {
        this.isarchive = isarchive;
    }
    public int getDeleteflag() {
        return this.deleteflag;
    }

    public void setDeleteflag(int deleteflag) {
        this.deleteflag = deleteflag;
    }
    
    public int getValidflag() {
        return this.validflag;
    }

    public void setValidflag(int validflag) {
        this.validflag = validflag;
    }

    public String getCellstyle() {
        return cellstyle;
    }

    public void setCellstyle(String cellstyle) {
        this.cellstyle = cellstyle;
    }

    public Set getAccountOwners() {
        return accountOwners;
    }

    public void setAccountOwners(Set accountOwners) {
        this.accountOwners = accountOwners;
    }

    public Set getCrmProducts() {
        return crmProducts;
    }

    public void setCrmProducts(Set crmProducts) {
        this.crmProducts = crmProducts;
    }
    
    public User getAccountmainowner() {
        User mainOwner = null;
        for(accountOwners accOwner : this.accountOwners) {
            if(accOwner.isMainOwner()) {
                mainOwner = accOwner.getUsersByUserid();
                break;
            }
        }
        return mainOwner;
    }
}
