/*
 * Copyright (C) 2012  Krawler Information Systems Pvt Ltd
 * All rights reserved.
 * 
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License
 * as published by the Free Software Foundation; either version 2
 * of the License, or (at your option) any later version.
 * 
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 * 
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
*/
package com.krawler.crm.database.tables; 
// Generated Jul 9, 2009 7:57:07 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;
import com.krawler.common.admin.*;
import com.krawler.common.stats.StatUtil;
/**
 * CrmCampaign generated by hbm2java
 */
public class CrmCampaign  implements java.io.Serializable {
	 private static final long serialVersionUID = 1L;
	 private String campaignid;
     private User usersByUpdatedbyid;
     private User usersByCreatedbyid;
     private Company company;
     private DefaultMasterItem crmCombodataByCampaignstatusid;
     private User usersByUserid;
     private DefaultMasterItem crmCombodataByCampaigntypeid;
     private String campaignname;
     private String description;
     private String active;
     private String numsent;
     private String expectedresponse;
     private String expectedrevenue;
     private String budgetedcost;
     private String actualcost;
     private Long createdOn;
     private Long updatedOn;
     private String objective;
     private String campaignresponse;
     private String totalresponse;
     private String totalleads;
     private String convertedleads;
     private String totalcontacts;
     private String totalopportunity;
     private String wonopportunity;
     private boolean isarchive;
     private int deleteflag;
     private Long startingdate;
     private Long endingdate;
     private int validflag;
     private String cellstyle;

     
    public CrmCampaign() {
    }

    public String getCampaignid() {
        return this.campaignid;
    }

    public void setCampaignid(String campaignid) {
        this.campaignid = campaignid;
    }
    public User getUsersByUpdatedbyid() {
        return this.usersByUpdatedbyid;
    }

    public void setUsersByUpdatedbyid(User usersByUpdatedbyid) {
        this.usersByUpdatedbyid = usersByUpdatedbyid;
    }
    public User getUsersByCreatedbyid() {
        return this.usersByCreatedbyid;
    }

    public void setUsersByCreatedbyid(User usersByCreatedbyid) {
        this.usersByCreatedbyid = usersByCreatedbyid;
    }

    public Company getCompany() {
        return this.company;
    }

    public void setCompany(Company company) {
        this.company = company;
    }
    public DefaultMasterItem getCrmCombodataByCampaignstatusid() {
        return this.crmCombodataByCampaignstatusid;
    }

    public void setCrmCombodataByCampaignstatusid(DefaultMasterItem crmCombodataByCampaignstatusid) {
        this.crmCombodataByCampaignstatusid = crmCombodataByCampaignstatusid;
    }
    public User getUsersByUserid() {
        return this.usersByUserid;
    }

    public void setUsersByUserid(User usersByUserid) {
        this.usersByUserid = usersByUserid;
    }
    public DefaultMasterItem getCrmCombodataByCampaigntypeid() {
        return this.crmCombodataByCampaigntypeid;
    }

    public void setCrmCombodataByCampaigntypeid(DefaultMasterItem crmCombodataByCampaigntypeid) {
        this.crmCombodataByCampaigntypeid = crmCombodataByCampaigntypeid;
    }
    public String getCampaignname() {
        return this.campaignname;
    }

    public void setCampaignname(String campaignname) {
        this.campaignname = campaignname;
    }
    public String getDescription() {
        return this.description;
    }

    public void setDescription(String description) {
        this.description = description;
    }
    public String getActive() {
        return this.active;
    }

    public void setActive(String active) {
        this.active = active;
    }
    public String getNumsent() {
        return this.numsent;
    }

    public void setNumsent(String numsent) {
        this.numsent = numsent;
    }
    public String getExpectedresponse() {
        return this.expectedresponse;
    }

    public void setExpectedresponse(String expectedresponse) {
        this.expectedresponse = expectedresponse;
    }
    public String getExpectedrevenue() {
        return this.expectedrevenue;
    }

    public void setExpectedrevenue(String expectedrevenue) {
        this.expectedrevenue = expectedrevenue;
    }
    public String getBudgetedcost() {
        return this.budgetedcost;
    }

    public void setBudgetedcost(String budgetedcost) {
        this.budgetedcost = budgetedcost;
    }
    public String getActualcost() {
        return this.actualcost;
    }

    public void setActualcost(String actualcost) {
        this.actualcost = actualcost;
    }

    public Long getCreatedOn() {
        return createdOn;
    }

    public void setCreatedOn(Long createdOn) {
        this.createdOn = createdOn;
    }

    public Long getUpdatedOn() {
        return updatedOn;
    }

    public void setUpdatedOn(Long updatedOn) {
        this.updatedOn = updatedOn;
    }


    public Date getCreatedon() {
        if(this.createdOn!=null)
            return new Date(this.createdOn);
        return null;
    }
    public String getCreatedonGMT() {
        return StatUtil.DATE_FORMAT_GMT.format(getCreatedon());
    }
    public void setCreatedon(Date createdon) {
        this.createdOn = createdon.getTime();
    }
    public Date getUpdatedon() {
        if(this.updatedOn!=null)
            return new Date(this.updatedOn);
        return null;
    }

    public void setUpdatedon(Date updatedon) {
        this.updatedOn = updatedon.getTime();
    }
    public String getObjective() {
        return this.objective;
    }

    public void setObjective(String objective) {
        this.objective = objective;
    }
    public String getCampaignresponse() {
        return this.campaignresponse;
    }

    public void setCampaignresponse(String campaignresponse) {
        this.campaignresponse = campaignresponse;
    }
    public String getTotalresponse() {
        return this.totalresponse;
    }

    public void setTotalresponse(String totalresponse) {
        this.totalresponse = totalresponse;
    }
    public String getTotalleads() {
        return this.totalleads;
    }

    public void setTotalleads(String totalleads) {
        this.totalleads = totalleads;
    }
    public String getConvertedleads() {
        return this.convertedleads;
    }

    public void setConvertedleads(String convertedleads) {
        this.convertedleads = convertedleads;
    }
    public String getTotalcontacts() {
        return this.totalcontacts;
    }

    public void setTotalcontacts(String totalcontacts) {
        this.totalcontacts = totalcontacts;
    }
    public String getTotalopportunity() {
        return this.totalopportunity;
    }

    public void setTotalopportunity(String totalopportunity) {
        this.totalopportunity = totalopportunity;
    }
    public String getWonopportunity() {
        return this.wonopportunity;
    }

    public void setWonopportunity(String wonopportunity) {
        this.wonopportunity = wonopportunity;
    }

    public boolean getIsarchive() {
        return this.isarchive;
    }

    public void setIsarchive(boolean isarchive) {
        this.isarchive = isarchive;
    }
    public int getDeleteflag() {
        return this.deleteflag;
    }

    public void setDeleteflag(int deleteflag) {
        this.deleteflag = deleteflag;
    }
    
	public Long getStartingdate() {
		return startingdate;
	}

	public void setStartingdate(Long startingdate) {
		this.startingdate = startingdate;
	}

	public Long getEndingdate() {
		return endingdate;
	}

	public void setEndingdate(Long endingdate) {
		this.endingdate = endingdate;
	}
	
    public int getValidflag() {
        return this.validflag;
    }

    public void setValidflag(int validflag) {
        this.validflag = validflag;
    }

    public String getCellstyle() {
        return cellstyle;
    }

    public void setCellstyle(String cellstyle) {
        this.cellstyle = cellstyle;
    }


}
