/*
 * Copyright (C) 2012  Krawler Information Systems Pvt Ltd
 * All rights reserved.
 * 
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License
 * as published by the Free Software Foundation; either version 2
 * of the License, or (at your option) any later version.
 * 
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 * 
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
*/
package com.krawler.crm.database.tables; 
// Generated Jul 9, 2009 7:57:07 PM by Hibernate Tools 3.2.1.GA


import java.io.Serializable;
import java.util.Date;
import com.krawler.common.admin.*;
import com.krawler.common.stats.StatUtil;
import java.util.HashSet;
import java.util.Set;
/**
 * CrmOpportunity generated by hbm2java
 */
public class CrmOpportunity  implements java.io.Serializable {


     private String oppid;
     private CrmProduct crmProduct;
     private DefaultMasterItem crmCombodataByOppstageid;
     private DefaultMasterItem crmCombodataByOpptypeid;
     private DefaultMasterItem crmCombodataByLeadsourceid;
     private DefaultMasterItem crmCombodataByRegionid;
     private String regionID;
     private String oppstageID;
     private String opptypeID;
     private String leadsourceID;
     private User usersByUpdatedbyid;
     private User usersByCreatedbyid;
     private CrmLead crmLead;
     private CrmAccount crmAccount;
     private Company company;
     private Set crmProducts = new HashSet();
     private Set<opportunityOwners> oppOwners = new HashSet();
     private String oppname;
     private String closedate;
     private String probability;
     private String currencyid;
     private String revenue;
     private String recurrevenue;
     private String price;
     private String keyname;
     private String keytitleid;
     private String keyaddstreet;
     private String keyaddcity;
     private String keyaddstate;
     private String keyaddcountry;
     private String keyaddzip;
     private String description;
     private String competitorname;
     private String salesamount;
     private boolean isarchive;
//     private Date updatedon;
//     private Date createdon;
     private Long updatedOn;
     private Long createdOn;
     private int deleteflag;
     private Long closingdate;
     private Date closindate;
     private int validflag;
     private String cellstyle;
     private CrmOpportunityCustomData CrmOpportunityCustomDataobj;
     private Double revenuenum;
     private Double pricenum;
     private Double salesamountnum;
     private Double probabilitynum;


    private String companyid;
    public String getCompanyid() {
        return companyid;
    }

    public void setCompanyid(String companyid) {
        this.companyid = companyid;
    }
    public CrmOpportunity() {
    }

    public CrmOpportunity(String oppid, DefaultMasterItem crmCombodataByOppstageid, DefaultMasterItem crmCombodataByOpptypeid, User usersByUpdatedbyid, User usersByCreatedbyid, CrmLead crmLead, CrmAccount crmAccount, Company company, CrmProduct crmProduct, DefaultMasterItem crmCombodataByLeadsourceid, User usersByUserid, String oppname, String closedate, String probability, String currencyid, String revenue, String recurrevenue, String price, String keyname, String keytitleid, String keyaddstreet, String keyaddcity, String keyaddstate, String keyaddcountry, String keyaddzip, String description, String competitorname, String salesamount, boolean isarchive, Long updatedOn, Long createdOn, int deleteflag, Long closingdate,int validflag) {
        this.oppid = oppid;
        this.crmCombodataByOppstageid = crmCombodataByOppstageid;
        this.crmCombodataByOpptypeid = crmCombodataByOpptypeid;
        this.usersByUpdatedbyid = usersByUpdatedbyid;
        this.usersByCreatedbyid = usersByCreatedbyid;
        this.crmLead = crmLead;
        this.crmAccount = crmAccount;
        this.company = company;
        this.crmCombodataByLeadsourceid = crmCombodataByLeadsourceid;
        this.oppname = oppname;
        this.closedate = closedate;
        this.probability = probability;
        this.currencyid = currencyid;
        this.revenue = revenue;
        this.recurrevenue = recurrevenue;
        this.price = price;
        this.keyname = keyname;
        this.keytitleid = keytitleid;
        this.keyaddstreet = keyaddstreet;
        this.keyaddcity = keyaddcity;
        this.keyaddstate = keyaddstate;
        this.keyaddcountry = keyaddcountry;
        this.keyaddzip = keyaddzip;
        this.description = description;
        this.competitorname = competitorname;
        this.salesamount = salesamount;
        this.isarchive = isarchive;
        this.updatedOn = updatedOn;
        this.createdOn = createdOn;
        this.deleteflag = deleteflag;
        this.closingdate = closingdate;
        this.validflag=validflag;
    }

    public Double getProbabilitynum() {
        try {
            return Double.parseDouble(this.getProbability());
        } catch(Exception ex) {
            return Double.parseDouble("0");
        }
    }

    public void setProbabilitynum(Double probabilitynum) {
        this.probabilitynum = probabilitynum;
    }

    public Double getRevenuenum() {
        try {
            return Double.parseDouble(this.getRevenue());
        } catch(Exception ex) {
            return Double.parseDouble("0");
        }
    }

    public void setRevenuenum(Double revenuenum) {
        this.revenuenum = revenuenum;
    }

    public Double getPricenum() {
        try {
            return Double.parseDouble(this.getPrice());
        } catch(Exception ex) {
            return Double.parseDouble("0");
        }
    }
    
    public void setPricenum(Double pricenum) {
        this.pricenum = pricenum;
    }

    public Double getSalesamountnum() {
        try {
            return Double.parseDouble(this.getSalesamount());
        } catch(Exception ex) {
            return Double.parseDouble("0");
        }
    }

    public void setSalesamountnum(Double salesamountnum) {
        this.salesamountnum = salesamountnum;
    }

    public DefaultMasterItem getCrmCombodataByRegionid() {
        return crmCombodataByRegionid;
    }

    public void setCrmCombodataByRegionid(DefaultMasterItem crmCombodataByRegionid) {
        this.crmCombodataByRegionid = crmCombodataByRegionid;
    }

    public String getRegionID() {
        return regionID;
    }

    public void setRegionID(String regionID) {
        this.regionID = regionID;
    }

    public CrmProduct getCrmProduct() {
        return this.crmProduct;
    }

    public void setCrmProduct(CrmProduct crmProduct) {
        this.crmProduct = crmProduct;
    }

    public String getLeadsourceID() {
        return leadsourceID;
    }

    public void setLeadsourceID(String leadsourceID) {
        this.leadsourceID = leadsourceID;
    }

    public String getOppstageID() {
        return oppstageID;
    }

    public void setOppstageID(String oppstageID) {
        this.oppstageID = oppstageID;
    }

    public String getOpptypeID() {
        return opptypeID;
    }

    public void setOpptypeID(String opptypeID) {
        this.opptypeID = opptypeID;
    }

    public CrmOpportunityCustomData getCrmOpportunityCustomDataobj() {
        return CrmOpportunityCustomDataobj;
    }

    public void setCrmOpportunityCustomDataobj(CrmOpportunityCustomData CrmOpportunityCustomDataobj) {
        this.CrmOpportunityCustomDataobj = CrmOpportunityCustomDataobj;
    }


    public String getOppid() {
        return this.oppid;
    }

    public void setOppid(String oppid) {
        this.oppid = oppid;
    }
    public DefaultMasterItem getCrmCombodataByOppstageid() {
        return this.crmCombodataByOppstageid;
    }

    public void setCrmCombodataByOppstageid(DefaultMasterItem crmCombodataByOppstageid) {
        this.crmCombodataByOppstageid = crmCombodataByOppstageid;
    }
    public DefaultMasterItem getCrmCombodataByOpptypeid() {
        return this.crmCombodataByOpptypeid;
    }

    public void setCrmCombodataByOpptypeid(DefaultMasterItem crmCombodataByOpptypeid) {
        this.crmCombodataByOpptypeid = crmCombodataByOpptypeid;
    }
    public User getUsersByUpdatedbyid() {
        return this.usersByUpdatedbyid;
    }

    public void setUsersByUpdatedbyid(User usersByUpdatedbyid) {
        this.usersByUpdatedbyid = usersByUpdatedbyid;
    }
    public User getUsersByCreatedbyid() {
        return this.usersByCreatedbyid;
    }

    public void setUsersByCreatedbyid(User usersByCreatedbyid) {
        this.usersByCreatedbyid = usersByCreatedbyid;
    }
    public CrmLead getCrmLead() {
        return this.crmLead;
    }

    public void setCrmLead(CrmLead crmLead) {
        this.crmLead = crmLead;
    }
    public CrmAccount getCrmAccount() {
        return this.crmAccount;
    }

    public void setCrmAccount(CrmAccount crmAccount) {
        this.crmAccount = crmAccount;
    }
    public Company getCompany() {
        return this.company;
    }

    public void setCompany(Company company) {
        this.company = company;
    }
    public DefaultMasterItem getCrmCombodataByLeadsourceid() {
        return this.crmCombodataByLeadsourceid;
    }

    public void setCrmCombodataByLeadsourceid(DefaultMasterItem crmCombodataByLeadsourceid) {
        this.crmCombodataByLeadsourceid = crmCombodataByLeadsourceid;
    }
    public String getOppname() {
        return this.oppname;
    }

    public void setOppname(String oppname) {
        this.oppname = oppname;
    }
    public String getClosedate() {
        return this.closedate;
    }

    public void setClosedate(String closedate) {
        this.closedate = closedate;
    }
    public String getProbability() {
        return this.probability;
    }

    public void setProbability(String probability) {
        this.probability = probability;
    }
    public String getCurrencyid() {
        return this.currencyid;
    }

    public void setCurrencyid(String currencyid) {
        this.currencyid = currencyid;
    }
    public String getRevenue() {
        return this.revenue;
    }

    public void setRevenue(String revenue) {
        this.revenue = revenue;
    }
    public String getRecurrevenue() {
        return this.recurrevenue;
    }

    public void setRecurrevenue(String recurrevenue) {
        this.recurrevenue = recurrevenue;
    }
    public String getPrice() {
        return this.price;
    }

    public void setPrice(String price) {
        this.price = price;
    }
    public String getKeyname() {
        return this.keyname;
    }

    public void setKeyname(String keyname) {
        this.keyname = keyname;
    }
    public String getKeytitleid() {
        return this.keytitleid;
    }

    public void setKeytitleid(String keytitleid) {
        this.keytitleid = keytitleid;
    }
    public String getKeyaddstreet() {
        return this.keyaddstreet;
    }

    public void setKeyaddstreet(String keyaddstreet) {
        this.keyaddstreet = keyaddstreet;
    }
    public String getKeyaddcity() {
        return this.keyaddcity;
    }

    public void setKeyaddcity(String keyaddcity) {
        this.keyaddcity = keyaddcity;
    }
    public String getKeyaddstate() {
        return this.keyaddstate;
    }

    public void setKeyaddstate(String keyaddstate) {
        this.keyaddstate = keyaddstate;
    }
    public String getKeyaddcountry() {
        return this.keyaddcountry;
    }

    public void setKeyaddcountry(String keyaddcountry) {
        this.keyaddcountry = keyaddcountry;
    }
    public String getKeyaddzip() {
        return this.keyaddzip;
    }

    public void setKeyaddzip(String keyaddzip) {
        this.keyaddzip = keyaddzip;
    }
    public String getDescription() {
        return this.description;
    }

    public void setDescription(String description) {
        this.description = description;
    }
    public String getCompetitorname() {
        return this.competitorname;
    }

    public void setCompetitorname(String competitorname) {
        this.competitorname = competitorname;
    }
    public String getSalesamount() {
        return this.salesamount;
    }

    public void setSalesamount(String salesamount) {
        this.salesamount = salesamount;
    }
    public boolean getIsarchive() {
        return this.isarchive;
    }

    public void setIsarchive(boolean isarchive) {
        this.isarchive = isarchive;
    }

    public Long getCreatedOn() {
        return createdOn;
    }

    public void setCreatedOn(Long createdOn) {
        this.createdOn = createdOn;
    }

    public Long getUpdatedOn() {
        return updatedOn;
    }

    public void setUpdatedOn(Long updatedOn) {
        this.updatedOn = updatedOn;
    }

    public Date getUpdatedon() {
        if(this.updatedOn!=null)
            return new Date(this.updatedOn);
        return null;
    }

    public void setUpdatedon(Date updatedon) {
        this.updatedOn = updatedon.getTime();
    }
    public Date getCreatedon() {
        if(this.createdOn!=null)
            return new Date(this.createdOn);
        return null;
    }
    public String getCreatedonGMT() {
        return StatUtil.DATE_FORMAT_GMT.format(getCreatedon());
    }

    public void setCreatedon(Date createdon) {
        this.createdOn = createdon.getTime();
    }
    public int getDeleteflag() {
        return this.deleteflag;
    }

    public void setDeleteflag(int deleteflag) {
        this.deleteflag = deleteflag;
    }
//    public  getClosindate() {
//        return closingdate;
//    }
//    
    public String getClosindateGMT() {
        return StatUtil.DATE_FORMAT_GMT.format(getClosingdate());
    }

//    public void setClosindate(Date closindate) {
//        this.closingdate = closingdate;
//    }
//   
    public int getValidflag() {
        return this.validflag;
    }

    public void setValidflag(int validflag) {
        this.validflag = validflag;
    }

    public String getCellstyle() {
        return cellstyle;
    }

    public void setCellstyle(String cellstyle) {
        this.cellstyle = cellstyle;
    }

    public Set getCrmProducts() {
        return crmProducts;
    }

    public void setCrmProducts(Set crmProduct) {
        this.crmProducts = crmProduct;
    }

    public Set getOppOwners() {
        return oppOwners;
    }

    public void setOppOwners(Set oppOwners) {
        this.oppOwners = oppOwners;
    }

    public Long getClosingdate() {
		return closingdate;
	}

	public void setClosingdate(Long closingdate) {
		this.closingdate = closingdate;
	}
	
	public Date getClosingDate() {      // please don't change method name it is used in db  as html message for mail sending when opp created and owner has changed.
		 if(closingdate!=null)
	       closindate=new Date(this.closingdate);
		 return closindate;
	}

    public void setClosingDate(Date closindate) {
	        this.closingdate =closindate.getTime();
	}

	public void setClosindate(Date closindate) {
	        this.closingdate =closindate.getTime();
	}

	public User getOppmainowner() {
        User mainOwner = null;
        for(opportunityOwners oppOwner : this.oppOwners) {
            if(oppOwner.isMainOwner()) {
                mainOwner = oppOwner.getUsersByUserid();
                break;
            }
        }
        return mainOwner;
    }

}
