/*
 * Copyright (C) 2012  Krawler Information Systems Pvt Ltd
 * All rights reserved.
 * 
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License
 * as published by the Free Software Foundation; either version 2
 * of the License, or (at your option) any later version.
 * 
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 * 
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
*/
package com.krawler.crm.database.tables; 
// Generated Jul 9, 2009 7:57:07 PM by Hibernate Tools 3.2.1.GA


import java.io.Serializable;
import java.util.Date;
import com.krawler.common.admin.*;
/**
 * CrmActivityMaster generated by hbm2java
 */
public class CrmActivityMaster  implements java.io.Serializable {


     private String activityid;
     private User usersByUpdatedbyid;
     private DefaultMasterItem crmCombodataByPriorityid;
     private DefaultMasterItem crmCombodataByStatusid;
     private DefaultMasterItem crmCombodataByTypeid;
     private String priorityID;
     private String statusID;
     private String typeID;
     private User usersByCreatedbyid;
     private Company company;
     private User usersByUserid;
     private String flag;
     private String subject;
     private String phone;
     private String email;
     private Long startDate;
     private Long endDate;
     private String name;
     private String comments;
     private Long updatedOn;
     private Long createdOn;
     private boolean isarchive;
     private int deleteflag;
     private int validflag;
     private int mapwith;
     private String cellstyle;
     private int scheduleType;
     private boolean isallday;
     private Date tilldate;
     private Long tilldat;
     private String calendarid;

    public CrmActivityMaster() {
    }


    public CrmActivityMaster(String activityid, User usersByUpdatedbyid, DefaultMasterItem crmCombodataByPriorityid, User usersByCreatedbyid, DefaultMasterItem crmCombodataByStatusid, Company company, User usersByUserid, DefaultMasterItem crmCombodataByTypeid, String flag, String subject, String phone, String email, Long startDate, Long endDate, String starttime, String endtime, String name, Long updatedOn, Long createdOn, boolean isarchive,int deleteflag,int validflag,int mapwith) {
        this.activityid = activityid;
        this.usersByUpdatedbyid = usersByUpdatedbyid;
        this.crmCombodataByPriorityid = crmCombodataByPriorityid;
        this.usersByCreatedbyid = usersByCreatedbyid;
        this.crmCombodataByStatusid = crmCombodataByStatusid;
        this.company = company;
        this.usersByUserid = usersByUserid;
        this.crmCombodataByTypeid = crmCombodataByTypeid;
        this.flag = flag;
        this.subject = subject;
        this.phone = phone;
        this.email = email;
        this.startDate = startDate;
        this.endDate = endDate;
        this.name = name;
        this.updatedOn = updatedOn;
        this.createdOn = createdOn;
        this.isarchive = isarchive;
        this.deleteflag = deleteflag;
        this.validflag=validflag;
        this.mapwith=mapwith;
    }

    public String getPriorityID() {
        return priorityID;
    }

    public void setPriorityID(String priorityID) {
        this.priorityID = priorityID;
    }

    public String getStatusID() {
        return statusID;
    }

    public void setStatusID(String statusID) {
        this.statusID = statusID;
    }

    public String getTypeID() {
        return typeID;
    }

    public void setTypeID(String typeID) {
        this.typeID = typeID;
    }

    public String getActivityid() {
        return this.activityid;
    }

    public void setActivityid(String activityid) {
        this.activityid = activityid;
    }
    public User getUsersByUpdatedbyid() {
        return this.usersByUpdatedbyid;
    }

    public void setUsersByUpdatedbyid(User usersByUpdatedbyid) {
        this.usersByUpdatedbyid = usersByUpdatedbyid;
    }
    public DefaultMasterItem getCrmCombodataByPriorityid() {
        return this.crmCombodataByPriorityid;
    }

    public void setCrmCombodataByPriorityid(DefaultMasterItem crmCombodataByPriorityid) {
        this.crmCombodataByPriorityid = crmCombodataByPriorityid;
    }
    public User getUsersByCreatedbyid() {
        return this.usersByCreatedbyid;
    }

    public void setUsersByCreatedbyid(User usersByCreatedbyid) {
        this.usersByCreatedbyid = usersByCreatedbyid;
    }
    public DefaultMasterItem getCrmCombodataByStatusid() {
        return this.crmCombodataByStatusid;
    }

    public void setCrmCombodataByStatusid(DefaultMasterItem crmCombodataByStatusid) {
        this.crmCombodataByStatusid = crmCombodataByStatusid;
}
    public Company getCompany() {
        return this.company;
    }

    public void setCompany(Company company) {
        this.company = company;
    }
    public User getUsersByUserid() {
        return this.usersByUserid;
    }

    public void setUsersByUserid(User usersByUserid) {
        this.usersByUserid = usersByUserid;
    }
    public DefaultMasterItem getCrmCombodataByTypeid() {
        return this.crmCombodataByTypeid;
    }

    public void setCrmCombodataByTypeid(DefaultMasterItem crmCombodataByTypeid) {
        this.crmCombodataByTypeid = crmCombodataByTypeid;
    }
    public String getFlag() {
        return this.flag;
    }

    public void setFlag(String flag) {
        this.flag = flag;
    }
    public String getSubject() {
        return this.subject;
    }

    public void setSubject(String subject) {
        this.subject = subject;
    }
    public String getPhone() {
        return this.phone;
    }

    public void setPhone(String phone) {
        this.phone = phone;
    }
    public String getEmail() {
        return this.email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public Long getEndDate() {
        return endDate;
    }

    public void setEndDate(Long endDate) {
        this.endDate = endDate;
    }

    public Long getStartDate() {
        return startDate;
    }

    public void setStartDate(Long startDate) {
        this.startDate = startDate;
    }

    public Date getStartdate() {
        if(this.startDate!=null)
            return new Date(this.startDate);
        return null;
    }

    public void setStartdate(Date startdate) {
        this.startDate = startdate.getTime();
    }
    
    public Date getEnddate() {
        if(this.endDate!=null)
            return new Date(this.endDate);
        return null;
    }

    public void setEnddate(Date enddate) {
        this.endDate = enddate.getTime();
    }
    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }
    public String getComments() {
        return this.comments;
    }

    public void setComments(String comments) {
        this.comments = comments;
    }

    public Long getCreatedOn() {
        return createdOn;
    }

    public void setCreatedOn(Long createdOn) {
        this.createdOn = createdOn;
    }

    public Long getUpdatedOn() {
        return updatedOn;
    }

    public void setUpdatedOn(Long updatedOn) {
        this.updatedOn = updatedOn;
    }


    public Date getUpdatedon() {
        if(this.updatedOn!=null)
            return new Date(this.updatedOn);
        return null;
    }

    public void setUpdatedon(Date updatedon) {
        this.updatedOn = updatedon.getTime();
    }
    public Date getCreatedon() {
        if(this.createdOn!=null)
            return new Date(this.createdOn);
        return null;
    }

    public void setCreatedon(Date createdon) {
        this.createdOn = createdon.getTime();
    }

    public boolean getIsarchive() {
        return this.isarchive;
    }

    public void setIsarchive(boolean isarchive) {
        this.isarchive = isarchive;
    }
    public int getDeleteflag() {
        return this.deleteflag;
    }

    public void setDeleteflag(int deleteflag) {
        this.deleteflag = deleteflag;
    }
   
    public int getValidflag() {
        return this.validflag;
    }

    public void setValidflag(int validflag) {
        this.validflag = validflag;
    }

    public int getMapwith() {
        return this.mapwith;
    }

    public void setMapwith(int mapwith) {
        this.mapwith = mapwith;
    }

    public String getCellstyle() {
        return cellstyle;
    }

    public void setCellstyle(String cellstyle) {
        this.cellstyle = cellstyle;
    }

    public boolean isIsallday() {
        return isallday;
    }

    public void setIsallday(boolean isallday) {
        this.isallday = isallday;
    }

    public int getScheduleType() {
        return scheduleType;
    }

    public void setScheduleType(int scheduleType) {
        this.scheduleType = scheduleType;
    }

    public Date getTilldate() {
    	if(this.tilldat!=null)
            return new Date(this.tilldat);
        return null;
        
    }
    public void setTilldate(Date tilldate) {
    	if(tilldate!=null){
    		this.tilldat = tilldate.getTime();
    	}else{
    		this.tilldat=null;}
    }
    
    public Long getTilldat() {
		return tilldat;
	}


	public void setTilldat(Long tilldat) {
		this.tilldat = tilldat;
	}


	public String getCalendarid() {
        return calendarid;
    }

    public void setCalendarid(String calendarid) {
        this.calendarid = calendarid;
    }
    
}
