/*
 * Copyright (C) 2012  Krawler Information Systems Pvt Ltd
 * All rights reserved.
 * 
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License
 * as published by the Free Software Foundation; either version 2
 * of the License, or (at your option) any later version.
 * 
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 * 
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
*/
package com.krawler.crm.database.tables;
// Generated Jul 9, 2009 7:57:07 PM by Hibernate Tools 3.2.1.GA



/**
 * CrmContactActivity generated by hbm2java
 */
public class CrmContactActivity  implements java.io.Serializable {


     private String rid;
     private CrmContact crmContact;
     private CrmActivityMaster crmActivityMaster;

    public CrmContactActivity() {
    }

    public CrmContactActivity(String rid, CrmContact crmContact, CrmActivityMaster crmActivityMaster) {
       this.rid = rid;
       this.crmContact = crmContact;
       this.crmActivityMaster = crmActivityMaster;
    }
   
    public String getRid() {
        return this.rid;
    }
    
    public void setRid(String rid) {
        this.rid = rid;
    }
    public CrmContact getCrmContact() {
        return this.crmContact;
    }
    
    public void setCrmContact(CrmContact crmContact) {
        this.crmContact = crmContact;
    }
    public CrmActivityMaster getCrmActivityMaster() {
        return this.crmActivityMaster;
    }
    
    public void setCrmActivityMaster(CrmActivityMaster crmActivityMaster) {
        this.crmActivityMaster = crmActivityMaster;
    }




}


