/*
 * Copyright (C) 2012  Krawler Information Systems Pvt Ltd
 * All rights reserved.
 * 
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License
 * as published by the Free Software Foundation; either version 2
 * of the License, or (at your option) any later version.
 * 
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 * 
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
*/
package com.krawler.crm.database.tables; 
// Generated Jul 9, 2009 7:57:07 PM by Hibernate Tools 3.2.1.GA


import java.io.Serializable;
import java.util.Date;
import com.krawler.common.admin.*;
import com.krawler.common.stats.StatUtil;
import java.util.HashSet;
import java.util.Set;
/**
 * CrmContact generated by hbm2java
 */
public class CrmContact  implements java.io.Serializable {


     private String contactid;
     private User usersByUpdatedbyid;
     private User usersByCreatedbyid;
     private CrmLead crmLead;
     private CrmLead Lead;
     private Company company;
     private DefaultMasterItem crmCombodataByLeadsourceid;
     private DefaultMasterItem crmCombodataByIndustryid;
     private String leadsourceID;
     private String industryID;
     private CrmAccount crmAccount;
     private String reportstoid;
     private String firstname;
     private String lastname;
     private String title;
     private String phoneno;
     private String mobileno;
     private String email;
     private String website;
     private String mailstreet;
     private String mailcity;
     private String mailstate;
     private String mailcountry;
     private String mailzip;
     private String birthdate;
     private String department;
     private String description;
     private String turnover;
     private String currencyid;
     private String otherstreet;
     private String othercity;
     private String otherstate;
     private String othercountry;
     private String otherzip;
     private String homephone;
     private String otherphone;
     private String fax;
     private String timetocall;
//     private Date updatedon;
//     private Date createdon;
     private Long updatedOn;
     private Long createdOn;
     private boolean  isarchive;
     private int deleteflag;
     private int validflag;
     private String cellstyle;
     private Set contactOwners = new HashSet();
     private CrmContactCustomData CrmContactCustomDataobj;
     private String companyid;
     public String getCompanyid() {
        return companyid;
    }

    public void setCompanyid(String companyid) {
        this.companyid = companyid;
    }
    public CrmContactCustomData getCrmContactCustomDataobj() {
        return CrmContactCustomDataobj;
    }

    public String getLeadsourceID() {
        return leadsourceID;
    }

    public void setLeadsourceID(String leadsourceID) {
        this.leadsourceID = leadsourceID;
    }

    public String getIndustryID() {
        return industryID;
    }

    public void setIndustryID(String industryID) {
        this.industryID = industryID;
    }
    
    public void setCrmContactCustomDataobj(CrmContactCustomData CrmContactCustomDataobj) {
        this.CrmContactCustomDataobj = CrmContactCustomDataobj;
    }

    public Set getContactOwners() {
        return contactOwners;
    }

    public void setContactOwners(Set contactOwners) {
        this.contactOwners = contactOwners;
    }

    public CrmContact() {
    }


    public CrmContact(String contactid, User usersByUpdatedbyid, User usersByCreatedbyid, CrmLead crmLead, Company company, DefaultMasterItem crmCombodataByLeadsourceid, User usersByUserid, DefaultMasterItem crmCombodataByIndustryid, String reportstoid, String firstname, String lastname,String title, String phoneno, String mobileno, String email, String website, String mailstreet, String mailcity, String mailstate, String mailcountry, String mailzip, String birthdate, String department, String description, String turnover, String currencyid, String otherstreet, String othercity, String otherstate, String othercountry, String otherzip, String homephone, String otherphone, String fax, String timetocall, Long updatedOn, Long createdOn, boolean isarchive,int deleteflag,int validflag) {
        this.contactid = contactid;
        this.usersByUpdatedbyid = usersByUpdatedbyid;
        this.usersByCreatedbyid = usersByCreatedbyid;
        this.crmLead = crmLead;
        this.company = company;
        this.crmCombodataByLeadsourceid = crmCombodataByLeadsourceid;
        this.crmCombodataByIndustryid = crmCombodataByIndustryid;
        this.reportstoid = reportstoid;
        this.firstname = firstname;
        this.lastname = lastname;
        this.title = title;
        this.phoneno = phoneno;
        this.mobileno = mobileno;
        this.email = email;
        this.website = website;
        this.mailstreet = mailstreet;
        this.mailcity = mailcity;
        this.mailstate = mailstate;
        this.mailcountry = mailcountry;
        this.mailzip = mailzip;
        this.birthdate = birthdate;
        this.department = department;
        this.description = description;
        this.turnover = turnover;
        this.currencyid = currencyid;
        this.otherstreet = otherstreet;
        this.othercity = othercity;
        this.otherstate = otherstate;
        this.othercountry = othercountry;
        this.otherzip = otherzip;
        this.homephone = homephone;
        this.otherphone = otherphone;
        this.fax = fax;
        this.timetocall = timetocall;
        this.updatedOn = updatedOn;
        this.createdOn = createdOn;
        this.isarchive = isarchive;
        this.deleteflag = deleteflag;
        this.validflag=validflag;
    }

    public String getContactid() {
        return this.contactid;
    }

    public void setContactid(String contactid) {
        this.contactid = contactid;
    }
    public User getUsersByUpdatedbyid() {
        return this.usersByUpdatedbyid;
    }

    public void setUsersByUpdatedbyid(User usersByUpdatedbyid) {
        this.usersByUpdatedbyid = usersByUpdatedbyid;
    }
    public User getUsersByCreatedbyid() {
        return this.usersByCreatedbyid;
    }

    public void setUsersByCreatedbyid(User usersByCreatedbyid) {
        this.usersByCreatedbyid = usersByCreatedbyid;
    }
    public CrmLead getCrmLead() {
        return this.crmLead;
    }

    public void setCrmLead(CrmLead crmLead) {
        this.crmLead = crmLead;
    }
    public Company getCompany() {
        return this.company;
    }

    public void setCompany(Company company) {
        this.company = company;
    }
    public DefaultMasterItem getCrmCombodataByLeadsourceid() {
        return this.crmCombodataByLeadsourceid;
    }

    public void setCrmCombodataByLeadsourceid(DefaultMasterItem crmCombodataByLeadsourceid) {
        this.crmCombodataByLeadsourceid = crmCombodataByLeadsourceid;
    }
    public DefaultMasterItem getCrmCombodataByIndustryid() {
        return this.crmCombodataByIndustryid;
    }

    public void setCrmCombodataByIndustryid(DefaultMasterItem crmCombodataByIndustryid) {
        this.crmCombodataByIndustryid = crmCombodataByIndustryid;
    }
    public String getReportstoid() {
        return this.reportstoid;
    }

    public void setReportstoid(String reportstoid) {
        this.reportstoid = reportstoid;
    }
    public String getFirstname() {
        return this.firstname;
    }

    public void setFirstname(String firstname) {
        this.firstname = firstname;
    }
    public String getLastname() {
        return this.lastname;
    }
    public String getFullname() {
        return (this.firstname!=null?this.firstname:"")+" "+(this.lastname!=null?this.lastname:"");
    }
    public String getTitle() {
        return this.title;
    }

    public void setTitle(String title) {
        this.title = title;
    }
    public void setLastname(String lastname) {
        this.lastname = lastname;
    }
    public String getPhoneno() {
        return this.phoneno;
    }

    public void setPhoneno(String phoneno) {
        this.phoneno = phoneno;
    }
    public String getMobileno() {
        return this.mobileno;
    }

    public void setMobileno(String mobileno) {
        this.mobileno = mobileno;
    }
    public String getEmail() {
        return this.email;
    }

    public void setEmail(String email) {
        this.email = email;
    }
    public String getWebsite() {
        return this.website;
    }

    public void setWebsite(String website) {
        this.website = website;
    }
    public String getMailstreet() {
        return this.mailstreet;
    }

    public void setMailstreet(String mailstreet) {
        this.mailstreet = mailstreet;
    }
    public String getMailcity() {
        return this.mailcity;
    }

    public void setMailcity(String mailcity) {
        this.mailcity = mailcity;
    }
    public String getMailstate() {
        return this.mailstate;
    }

    public void setMailstate(String mailstate) {
        this.mailstate = mailstate;
    }
    public String getMailcountry() {
        return this.mailcountry;
    }

    public void setMailcountry(String mailcountry) {
        this.mailcountry = mailcountry;
    }
    public String getMailzip() {
        return this.mailzip;
    }

    public void setMailzip(String mailzip) {
        this.mailzip = mailzip;
    }
    public String getBirthdate() {
        return this.birthdate;
    }

    public void setBirthdate(String birthdate) {
        this.birthdate = birthdate;
    }
    public String getDepartment() {
        return this.department;
    }

    public void setDepartment(String department) {
        this.department = department;
    }
    public String getDescription() {
        return this.description;
    }

    public void setDescription(String description) {
        this.description = description;
    }
    public String getTurnover() {
        return this.turnover;
    }

    public void setTurnover(String turnover) {
        this.turnover = turnover;
    }
    public String getCurrencyid() {
        return this.currencyid;
    }

    public void setCurrencyid(String currencyid) {
        this.currencyid = currencyid;
    }
    public String getOtherstreet() {
        return this.otherstreet;
    }

    public void setOtherstreet(String otherstreet) {
        this.otherstreet = otherstreet;
    }
    public String getOthercity() {
        return this.othercity;
    }

    public void setOthercity(String othercity) {
        this.othercity = othercity;
    }
    public String getOtherstate() {
        return this.otherstate;
    }

    public void setOtherstate(String otherstate) {
        this.otherstate = otherstate;
    }
    public String getOthercountry() {
        return this.othercountry;
    }

    public void setOthercountry(String othercountry) {
        this.othercountry = othercountry;
    }
    public String getOtherzip() {
        return this.otherzip;
    }

    public void setOtherzip(String otherzip) {
        this.otherzip = otherzip;
    }
    public String getHomephone() {
        return this.homephone;
    }

    public void setHomephone(String homephone) {
        this.homephone = homephone;
    }
    public String getOtherphone() {
        return this.otherphone;
    }

    public void setOtherphone(String otherphone) {
        this.otherphone = otherphone;
    }
    public String getFax() {
        return this.fax;
    }

    public void setFax(String fax) {
        this.fax = fax;
    }
    public String getTimetocall() {
        return this.timetocall;
    }

    public void setTimetocall(String timetocall) {
        this.timetocall = timetocall;
    }

    public Long getCreatedOn() {
        return createdOn;
    }

    public void setCreatedOn(Long createdOn) {
        this.createdOn = createdOn;
    }

    public Long getUpdatedOn() {
        return updatedOn;
    }

    public void setUpdatedOn(Long updatedOn) {
        this.updatedOn = updatedOn;
    }


    public Date getUpdatedon() {
        if(this.updatedOn!=null)
            return new Date(this.updatedOn);
        return null;
    }

    public void setUpdatedon(Date updatedon) {
        this.updatedOn = updatedon.getTime();
    }
    public Date getCreatedon() {
        if(this.createdOn!=null)
            return new Date(this.createdOn);
        return null;
    }

    public String getCreatedonGMT() {
        return StatUtil.DATE_FORMAT_GMT.format(getCreatedon());
    }

    public void setCreatedon(Date createdon) {
        this.createdOn = createdon.getTime();
    }

    public boolean getIsarchive() {
        return this.isarchive;
    }

    public void setIsarchive(boolean isarchive) {
        this.isarchive = isarchive;
    }
    public int getDeleteflag() {
        return this.deleteflag;
    }

    public void setDeleteflag(int deleteflag) {
        this.deleteflag = deleteflag;
    }

    public int getValidflag() {
        return this.validflag;
    }

    public void setValidflag(int validflag) {
        this.validflag = validflag;
    }

    public CrmAccount getCrmAccount() {
        return this.crmAccount;
    }

    public void setCrmAccount(CrmAccount crmAccount) {
        this.crmAccount = crmAccount;
    }

    public String getStringObj(String objName){
        String obj = "";
        if(objName.equals("fname")){
            obj = this.firstname;
        } else if(objName.equals("lname")){
            obj = this.lastname;
        } else if(objName.equals("phone")){
            obj = this.phoneno;
        } else if(objName.equals("email")){
            obj = this.email;
        } else if(objName.equals("rname")){
            obj = this.company.getCompanyName();
        }

        return obj;
    }

    public String getCellstyle() {
        return cellstyle;
    }

    public void setCellstyle(String cellstyle) {
        this.cellstyle = cellstyle;
    }

    public CrmLead getLead() {
        return Lead;
    }

    public void setLead(CrmLead Lead) {
        this.Lead = Lead;
    }
}

