/*
 * Copyright (C) 2012  Krawler Information Systems Pvt Ltd
 * All rights reserved.
 * 
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License
 * as published by the Free Software Foundation; either version 2
 * of the License, or (at your option) any later version.
 * 
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 * 
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
*/
package com.krawler.crm.database.tables; 
// Generated Jul 9, 2009 7:57:07 PM by Hibernate Tools 3.2.1.GA


import java.io.Serializable;
import java.util.Date;
import com.krawler.common.admin.*;
import com.krawler.common.stats.StatUtil;
import java.util.HashSet;
import java.util.Set;
/**
 * CrmLead generated by hbm2java
 */
public class CrmLead  implements java.io.Serializable {


     private String leadid;
     private User usersByUpdatedbyid;
     private User usersByCreatedbyid;
     private String leadstatusID;
     private String leadsourceID;
     private String industryID;
     private String ratingID;
     private DefaultMasterItem crmCombodataByLeadstatusid;
     private DefaultMasterItem crmCombodataByLeadsourceid;
     private CrmProduct crmProduct;
     private DefaultMasterItem crmCombodataByIndustryid;
     private DefaultMasterItem crmCombodataByRatingid;
     private Company company;
     private String companyid;
     private User usersByPersonassigned;
//     private String firstname;
     private String lastname;
     private String firstname;
//     private String companyname;
     private String title;
     private String phone;
     private String email;
     private String website;
     private String mobileno;
     private String fax;
     private String addstreet;
     private String city;
     private String state;
     private String country;
     private String zip;
     private String revenue;
     private String description;
//     private Date createdon;
//     private Date updatedon;
     private Long createdOn;
     private Long convertedOn;
     private Long updatedOn;
     private String isconverted;
     private boolean isarchive;
     private String istransfered;
     private int deleteflag;
     private String potrevenue;
     private String nextstep;
     private String conversiontype;
     private int validflag;
     private String type;
     private String cellstyle;
     private String price;
     private Double revenuenum;
     private Double pricenum;
     private boolean ownerconfirm; // default true. If lead generated from web form and FCFS (First Come First Serve) lead routing option is selected then set false and if someone has accepted that lead then reset to true again
     private Set leadOwners = new HashSet();
     private CrmLeadCustomData CrmLeadCustomDataobj;
     private Set crmProducts = new HashSet();
    public CrmLead() {
    }


    public CrmLead(String leadid, User usersByUpdatedbyid, User usersByCreatedbyid, DefaultMasterItem crmCombodataByLeadstatusid, DefaultMasterItem crmCombodataByLeadsourceid, CrmProduct crmProduct, DefaultMasterItem crmCombodataByIndustryid, DefaultMasterItem crmCombodataByRatingid, Company company, User usersByPersonassigned, User usersByUserid, String firstname, String lastname, String companyname,String title, String phone, String email, String website, String mobileno, String fax, String addstreet, String city, String state, String country, String zip, String revenue, String description, Long createdOn, Long updatedOn, String isconverted, boolean isarchive, String istransfered, int deleteflag, String potrevenue, String nextstep,int validflag) {
        this.leadid = leadid;
        this.usersByUpdatedbyid = usersByUpdatedbyid;
        this.usersByCreatedbyid = usersByCreatedbyid;
        this.crmCombodataByLeadstatusid = crmCombodataByLeadstatusid;
        this.crmCombodataByLeadsourceid = crmCombodataByLeadsourceid;
        this.crmProduct = crmProduct;
        this.crmCombodataByIndustryid = crmCombodataByIndustryid;
        this.crmCombodataByRatingid = crmCombodataByRatingid;
        this.company = company;
        this.usersByPersonassigned = usersByPersonassigned;
//        this.firstname = firstname;
        this.lastname = lastname;
//        this.companyname = companyname;
        this.title = title;
        this.phone = phone;
        this.email = email;
        this.website = website;
        this.mobileno = mobileno;
        this.fax = fax;
        this.addstreet = addstreet;
        this.city = city;
        this.state = state;
        this.country = country;
        this.zip = zip;
        this.revenue = revenue;
        this.description = description;
        this.createdOn = createdOn;
        this.updatedOn = updatedOn;
        this.isconverted = isconverted;
        this.isarchive = isarchive;
        this.istransfered = istransfered;
        this.deleteflag = deleteflag;
        this.potrevenue = potrevenue;
        this.nextstep = nextstep;
        this.conversiontype = conversiontype;
        this.validflag=validflag;
    }

    public String getCompanyid() {
        return companyid;
    }

    public void setCompanyid(String companyid) {
        this.companyid = companyid;
    }

    public String getIndustryID() {
        return industryID;
    }

    public void setIndustryID(String industryID) {
        this.industryID = industryID;
    }

    public String getLeadsourceID() {
        return leadsourceID;
    }

    public void setLeadsourceID(String leadsourceID) {
        this.leadsourceID = leadsourceID;
    }

    public String getLeadstatusID() {
        return leadstatusID;
    }

    public void setLeadstatusID(String leadstatusID) {
        this.leadstatusID = leadstatusID;
    }

    public String getRatingID() {
        return ratingID;
    }

    public void setRatingID(String ratingID) {
        this.ratingID = ratingID;
    }

    public CrmLeadCustomData getCrmLeadCustomDataobj() {
        return CrmLeadCustomDataobj;
    }

    public void setCrmLeadCustomDataobj(CrmLeadCustomData CrmLeadCustomDataobj) {
        this.CrmLeadCustomDataobj = CrmLeadCustomDataobj;
    }

    public String getLeadid() {
        return this.leadid;
    }

    public void setLeadid(String leadid) {
        this.leadid = leadid;
    }

    public User getUsersByUpdatedbyid() {
        return this.usersByUpdatedbyid;
    }

    public void setUsersByUpdatedbyid(User usersByUpdatedbyid) {
        this.usersByUpdatedbyid = usersByUpdatedbyid;
    }
    public User getUsersByCreatedbyid() {
        return this.usersByCreatedbyid;
    }

    public void setUsersByCreatedbyid(User usersByCreatedbyid) {
        this.usersByCreatedbyid = usersByCreatedbyid;
    }
    public DefaultMasterItem getCrmCombodataByLeadstatusid() {
        return this.crmCombodataByLeadstatusid;
    }

    public void setCrmCombodataByLeadstatusid(DefaultMasterItem crmCombodataByLeadstatusid) {
        this.crmCombodataByLeadstatusid = crmCombodataByLeadstatusid;
    }
    public DefaultMasterItem getCrmCombodataByLeadsourceid() {
        return this.crmCombodataByLeadsourceid;
    }

    public void setCrmCombodataByLeadsourceid(DefaultMasterItem crmCombodataByLeadsourceid) {
        this.crmCombodataByLeadsourceid = crmCombodataByLeadsourceid;
    }
    public CrmProduct getCrmProduct() {
        return this.crmProduct;
    }

    public void setCrmProduct(CrmProduct crmProduct) {
        this.crmProduct = crmProduct;
    }
    public DefaultMasterItem getCrmCombodataByIndustryid() {
        return this.crmCombodataByIndustryid;
    }

    public void setCrmCombodataByIndustryid(DefaultMasterItem crmCombodataByIndustryid) {
        this.crmCombodataByIndustryid = crmCombodataByIndustryid;
    }

    public DefaultMasterItem getCrmCombodataByRatingid() {
        return this.crmCombodataByRatingid;
    }

    public void setCrmCombodataByRatingid(DefaultMasterItem crmCombodataByRatingid) {
        this.crmCombodataByRatingid = crmCombodataByRatingid;
    }

    public Company getCompany() {
        return this.company;
    }

    public void setCompany(Company company) {
        this.company = company;
    }
    public User getUsersByPersonassigned() {
        return this.usersByPersonassigned;
    }

    public void setUsersByPersonassigned(User usersByPersonassigned) {
        this.usersByPersonassigned = usersByPersonassigned;
    }

    public String getFirstname() {
        return firstname;
    }

    public void setFirstname(String firstname) {
        this.firstname = firstname;
    }
//    public String getFirstname() {
//        return this.firstname;
//    }
//
//    public void setFirstname(String firstname) {
//        this.firstname = firstname;
//    }

    public String getLastname() {
        return this.lastname;
    }

    public void setLastname(String lastname) {
        this.lastname = lastname;
    }
//    public String getCompanyname() {
//        return this.companyname;
//    }
//
//    public void setCompanyname(String companyname) {
//        this.companyname = companyname;
//    }
    public String getTitle() {
        return this.title;
    }

    public void setTitle(String title) {
        this.title = title;
    }
    public String getPhone() {
        return this.phone;
    }

    public void setPhone(String phone) {
        this.phone = phone;
    }
    public String getEmail() {
        return this.email;
    }

    public void setEmail(String email) {
        this.email = email;
    }
    public String getWebsite() {
        return this.website;
    }

    public void setWebsite(String website) {
        this.website = website;
    }
    public String getMobileno() {
        return this.mobileno;
    }

    public void setMobileno(String mobileno) {
        this.mobileno = mobileno;
    }
    public String getFax() {
        return this.fax;
    }

    public void setFax(String fax) {
        this.fax = fax;
    }
    public String getAddstreet() {
        return this.addstreet;
    }

    public void setAddstreet(String addstreet) {
        this.addstreet = addstreet;
    }
    public String getCity() {
        return this.city;
    }

    public void setCity(String city) {
        this.city = city;
    }
    public String getState() {
        return this.state;
    }

    public void setState(String state) {
        this.state = state;
    }
    public String getCountry() {
        return this.country;
    }

    public void setCountry(String country) {
        this.country = country;
    }
    public String getZip() {
        return this.zip;
    }

    public void setZip(String zip) {
        this.zip = zip;
    }
    public String getRevenue() {
        return this.revenue;
    }

    public void setRevenue(String revenue) {
        this.revenue = revenue;
    }
    public String getDescription() {
        return this.description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public Long getCreatedOn() {
        return createdOn;
    }

    public void setCreatedOn(Long createdOn) {
        this.createdOn = createdOn;
    }

    public void setConvertedOn(Long convertedOn) {
        this.convertedOn = convertedOn;
    }
    public Long getConvertedOn() {
          return convertedOn;
    }
    public Date getConvertedon() {
        if(this.convertedOn!=null)
            return new Date(this.convertedOn);
        return null;
    }
    public void setConvertedon(Date convertedon) {
        this.convertedOn = convertedon.getTime();
    }
    
    public Long getUpdatedOn() {
        return updatedOn;
    }

    public void setUpdatedOn(Long updatedOn) {
        this.updatedOn = updatedOn;
    }

    public Date getCreatedon() {
        if(this.createdOn!=null)
            return new Date(this.createdOn);
        return null;
    }

    public String getCreatedonGMT() {
        return StatUtil.DATE_FORMAT_GMT.format(getCreatedon());
    }

    public void setCreatedon(Date createdon) {
        this.createdOn = createdon.getTime();
    }
    public Date getUpdatedon() {
        if(this.updatedOn!=null)
            return new Date(this.updatedOn);
        return null;
    }

    public void setUpdatedon(Date updatedon) {
        this.updatedOn = updatedon.getTime();
    }
    public String getIsconverted() {
        return this.isconverted;
    }

    public void setIsconverted(String isconverted) {
        this.isconverted = isconverted;
    }
    public boolean getIsarchive() {
        return this.isarchive;
    }

    public void setIsarchive(boolean isarchive) {
        this.isarchive = isarchive;
    }
    public String getIstransfered() {
        return this.istransfered;
    }

    public void setIstransfered(String istransfered) {
        this.istransfered = istransfered;
    }
    public int getDeleteflag() {
        return this.deleteflag;
    }

    public void setDeleteflag(int deleteflag) {
        this.deleteflag = deleteflag;
    }
    public String getPotrevenue() {
        return this.potrevenue;
    }

    public void setPotrevenue(String potrevenue) {
        this.potrevenue = potrevenue;
    }
    public String getNextstep() {
        return this.nextstep;
    }

    public void setNextstep(String nextstep) {
        this.nextstep = nextstep;
    }
    public String getConversiontype() {
        return this.conversiontype;
    }

    public void setConversiontype(String conversiontype) {
        this.conversiontype = conversiontype;
    }

    public int getValidflag() {
        return this.validflag;
    }

    public void setValidflag(int validflag) {
        this.validflag = validflag;
    }

    public String getStringObj(String objName){
        String obj = "";
        if(objName.equals("lname")){
            obj = this.lastname;
        } else if(objName.equals("phone")){
            obj = this.phone;
        } else if(objName.equals("email")){
            obj = this.email;
        }
        return obj;
    }

    public String getCellstyle() {
        return cellstyle;
    }

    public void setCellstyle(String cellstyle) {
        this.cellstyle = cellstyle;
    }

    public String getPrice() {
        return price;
    }

    public void setPrice(String price) {
        this.price = price;
    }

    public Set getLeadOwners() {
        return leadOwners;
    }

    public void setLeadOwners(Set leadOwners) {
        this.leadOwners = leadOwners;
    }
    public String getType() {
        return type;
    }
    public void setType(String type) {
        this.type = type;
    }
     public Set getCrmProducts() {
        return crmProducts;
    }

    public void setCrmProducts(Set crmProducts) {
        this.crmProducts = crmProducts;
    }

    public Double getRevenuenum() {
        try {
            return Double.parseDouble(this.getRevenue());
        } catch(Exception ex) {
            return Double.parseDouble("0");
        }
    }

    public Double getPricenum() {
        try {
            return Double.parseDouble(this.getPrice());
        } catch(Exception ex) {
            return Double.parseDouble("0");
        }
    }
    public void setPricenum(Double pricenum) {
        this.pricenum = pricenum;
    }

    public void setRevenuenum(Double revenuenum) {
        this.revenuenum = revenuenum;
    }

    public boolean isOwnerconfirm() {
        return ownerconfirm;
    }

    public void setOwnerconfirm(boolean ownerconfirm) {
        this.ownerconfirm = ownerconfirm;
    }
}

