/*
 * Copyright (C) 2012  Krawler Information Systems Pvt Ltd
 * All rights reserved.
 * 
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License
 * as published by the Free Software Foundation; either version 2
 * of the License, or (at your option) any later version.
 * 
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 * 
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
*/
package com.krawler.crm.database.tables; 
// Generated Jul 9, 2009 7:57:07 PM by Hibernate Tools 3.2.1.GA


import java.io.Serializable;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import com.krawler.common.admin.*;
import com.krawler.common.stats.StatUtil;
/**
 * CrmCase generated by hbm2java
 */
public class CrmCase  implements java.io.Serializable {


     private String caseid;
     private CrmContact crmContact;
     private User usersByUpdatedbyid;
     private CrmProduct crmProduct;
     private User usersByCreatedbyid;
     private DefaultMasterItem crmCombodataByCasetypeid;
     private DefaultMasterItem crmCombodataByCasestatusid;
     private DefaultMasterItem crmCombodataByCasepriorityid;
     private String casetypeID;
     private String casestatusID;
     private String casepriorityID;
     private CrmAccount crmAccount;
     private Company company;     
     private User usersByUserid;
     private String casename;
     private String subject;
     private String reportedbyid;
     private User assignedto;
     private String resolution;
     private String phone;
     private String email;
     private String description;
     private String internalcomments;
     private String fileuploadid;
//     private Date updatedon;
//     private Date createdon;
     private Long updatedOn;
     private Long createdOn;
     private Long createdOnNE;//createdOnNE - This is used to store creationdate with time which will not changed after editing creation date from system.
     private boolean isarchive;
     private int deleteflag;
     private int validflag;
     private String cellstyle;
     private Set crmProducts = new HashSet();
     private CrmCaseCustomData CrmCaseCustomDataobj;
     private String companyid;
     private String caseCreatedBy;
     private int createdByFlag;
     public String getCompanyid() {
        return companyid;
    }

    public void setCompanyid(String companyid) {
        this.companyid = companyid;
    }
    public CrmCaseCustomData getCrmCaseCustomDataobj() {
        return CrmCaseCustomDataobj;
    }

    public void setCrmCaseCustomDataobj(CrmCaseCustomData CrmCaseCustomDataobj) {
        this.CrmCaseCustomDataobj = CrmCaseCustomDataobj;
    }

    public CrmCase() {
    }


    public CrmCase(String caseid, CrmContact crmContact, User usersByUpdatedbyid, CrmProduct crmProduct, User usersByCreatedbyid, DefaultMasterItem crmCombodataByCasetypeid, DefaultMasterItem crmCombodataByCasestatusid, CrmAccount crmAccount, User assignedto,Company company, DefaultMasterItem crmCombodataByCasepriorityid, User usersByUserid, String casename, String subject, String reportedbyid, String resolution, String phone, String email, String description, String internalcomments, String fileuploadid, Long updatedOn, Long createdOn, boolean isarchive,int deleteflag,int validflag) {
        this.caseid = caseid;
        this.crmContact = crmContact;
        this.usersByUpdatedbyid = usersByUpdatedbyid;
        this.crmProduct = crmProduct;
        this.usersByCreatedbyid = usersByCreatedbyid;
        this.crmCombodataByCasetypeid = crmCombodataByCasetypeid;
        this.crmCombodataByCasestatusid = crmCombodataByCasestatusid;
        this.crmAccount = crmAccount;
        this.assignedto=assignedto;
        this.company = company;
        this.crmCombodataByCasepriorityid = crmCombodataByCasepriorityid;
        this.usersByUserid = usersByUserid;
        this.casename = casename;
        this.subject = subject;
        this.reportedbyid = reportedbyid;
        this.resolution = resolution;
        this.phone = phone;
        this.email = email;
        this.description = description;
        this.internalcomments = internalcomments;
        this.fileuploadid = fileuploadid;
        this.updatedOn = updatedOn;
        this.createdOn = createdOn;
        this.isarchive = isarchive;
        this.deleteflag = deleteflag;
        this.validflag=validflag;
    }

    public String getCasepriorityID() {
        return casepriorityID;
    }

    public void setCasepriorityID(String casepriorityID) {
        this.casepriorityID = casepriorityID;
    }

    public String getCasestatusID() {
        return casestatusID;
    }

    public void setCasestatusID(String casestatusID) {
        this.casestatusID = casestatusID;
    }

    public String getCasetypeID() {
        return casetypeID;
    }

    public void setCasetypeID(String casetypeID) {
        this.casetypeID = casetypeID;
    }

    public String getCaseid() {
        return this.caseid;
    }

    public void setCaseid(String caseid) {
        this.caseid = caseid;
    }
    public CrmContact getCrmContact() {
        return this.crmContact;
    }

    public void setCrmContact(CrmContact crmContact) {
        this.crmContact = crmContact;
    }
    public User getUsersByUpdatedbyid() {
        return this.usersByUpdatedbyid;
    }

    public void setUsersByUpdatedbyid(User usersByUpdatedbyid) {
        this.usersByUpdatedbyid = usersByUpdatedbyid;
    }
    public CrmProduct getCrmProduct() {
        return this.crmProduct;
    }

    public void setCrmProduct(CrmProduct crmProduct) {
        this.crmProduct = crmProduct;
    }
    public User getUsersByCreatedbyid() {
        return this.usersByCreatedbyid;
    }

    public void setUsersByCreatedbyid(User usersByCreatedbyid) {
        this.usersByCreatedbyid = usersByCreatedbyid;
    }
    public DefaultMasterItem getCrmCombodataByCasetypeid() {
        return this.crmCombodataByCasetypeid;
    }

    public void setCrmCombodataByCasetypeid(DefaultMasterItem crmCombodataByCasetypeid) {
        this.crmCombodataByCasetypeid = crmCombodataByCasetypeid;
    }
    public DefaultMasterItem getCrmCombodataByCasestatusid() {
        return this.crmCombodataByCasestatusid;
    }

    public void setCrmCombodataByCasestatusid(DefaultMasterItem crmCombodataByCasestatusid) {
        this.crmCombodataByCasestatusid = crmCombodataByCasestatusid;
    }
    public CrmAccount getCrmAccount() {
        return this.crmAccount;
    }

    public String getCaseaccountname() {
        return (this.crmAccount!=null?this.crmAccount.getAccountname():"None");
    }

    public void setCrmAccount(CrmAccount crmAccount) {
        this.crmAccount = crmAccount;
    }
    public Company getCompany() {
        return this.company;
    }

    public void setCompany(Company company) {
        this.company = company;
    }
    public DefaultMasterItem getCrmCombodataByCasepriorityid() {
        return this.crmCombodataByCasepriorityid;
    }

    public void setCrmCombodataByCasepriorityid(DefaultMasterItem crmCombodataByCasepriorityid) {
        this.crmCombodataByCasepriorityid = crmCombodataByCasepriorityid;
    }
    public User getUsersByUserid() {
        return this.usersByUserid;
    }

    public void setUsersByUserid(User usersByUserid) {
        this.usersByUserid = usersByUserid;
    }
    public String getCasename() {
        return this.casename;
    }

    public void setCasename(String casename) {
        this.casename = casename;
    }
    public String getSubject() {
        return this.subject;
    }

    public void setSubject(String subject) {
        this.subject = subject;
    }
    public String getReportedbyid() {
        return this.reportedbyid;
    }

    public void setReportedbyid(String reportedbyid) {
        this.reportedbyid = reportedbyid;
    }
    public String getResolution() {
        return this.resolution;
    }

    public void setResolution(String resolution) {
        this.resolution = resolution;
    }
    public String getPhone() {
        return this.phone;
    }

    public void setPhone(String phone) {
        this.phone = phone;
    }
    public String getEmail() {
        return this.email;
    }

    public void setEmail(String email) {
        this.email = email;
    }
    public String getDescription() {
        return this.description;
    }

    public void setDescription(String description) {
        this.description = description;
    }
    public String getInternalcomments() {
        return this.internalcomments;
    }

    public void setInternalcomments(String internalcomments) {
        this.internalcomments = internalcomments;
    }
    public String getFileuploadid() {
        return this.fileuploadid;
    }

    public void setFileuploadid(String fileuploadid) {
        this.fileuploadid = fileuploadid;
    }

    public Long getCreatedOnNE() {
        return createdOnNE;
    }

    public void setCreatedOnNE(Long createdOnNE) {
        this.createdOnNE = createdOnNE;
    }

    public Long getCreatedOn() {
        return createdOn;
    }

    public void setCreatedOn(Long createdOn) {
        this.createdOn = createdOn;
    }

    public Long getUpdatedOn() {
        return updatedOn;
    }

    public void setUpdatedOn(Long updatedOn) {
        this.updatedOn = updatedOn;
    }

    public Date getUpdatedon() {
        if(this.updatedOn!=null)
            return new Date(this.updatedOn);
        return null;
    }

    public void setUpdatedon(Date updatedon) {
        this.updatedOn = updatedon.getTime();
    }
    public Date getCreatedon() {
        if(this.createdOn!=null)
            return new Date(this.createdOn);
        return null;
    }
    public String getCreatedonGMT() {
        return StatUtil.DATE_FORMAT_GMT.format(getCreatedon());
    }
    public void setCreatedon(Date createdon) {
        this.createdOn = createdon.getTime();
    }

    public boolean  getIsarchive() {
        return this.isarchive;
    }

    public void setIsarchive(boolean isarchive) {
        this.isarchive = isarchive;
    }
    public int getDeleteflag() {
        return this.deleteflag;
    }

    public void setDeleteflag(int deleteflag) {
        this.deleteflag = deleteflag;
    }

    public int getValidflag() {
        return this.validflag;
    }

    public void setValidflag(int validflag) {
        this.validflag = validflag;
    }

    public String getCellstyle() {
        return cellstyle;
    }

    public void setCellstyle(String cellstyle) {
        this.cellstyle = cellstyle;
    }

    public Set getCrmProducts() {
        return crmProducts;
    }

    public void setCrmProducts(Set crmProducts) {
        this.crmProducts = crmProducts;
    }

	public User getAssignedto() {
		return assignedto;
	}

	public void setAssignedto(User assignedto) {
		this.assignedto = assignedto;
	}

	public String getCaseCreatedBy() {
		return caseCreatedBy;
	}

	public void setCaseCreatedBy(String caseCreatedBy) {
		this.caseCreatedBy = caseCreatedBy;
	}

	public int getCreatedByFlag() {
		return createdByFlag;
	}

	public void setCreatedByFlag(int createdByFlag) {
		this.createdByFlag = createdByFlag;
	}

}

