/*
 * Copyright (C) 2012  Krawler Information Systems Pvt Ltd
 * All rights reserved.
 * 
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License
 * as published by the Free Software Foundation; either version 2
 * of the License, or (at your option) any later version.
 * 
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 * 
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
*/
package com.krawler.crm.database.tables; 
// Generated Jul 9, 2009 7:57:07 PM by Hibernate Tools 3.2.1.GA


import java.io.Serializable;
import java.util.Date;
import com.krawler.common.admin.*;
import com.krawler.common.stats.StatUtil;
/**
 * CrmProduct generated by hbm2java
 */
public class CrmProduct  implements java.io.Serializable {


     private String productid;
     private User usersByUpdatedbyid;
     private User usersByCreatedbyid;
     private Company company;
     private User usersByUserid;
     private DefaultMasterItem crmCombodataByCategoryid;
     private String productcategoryID;
     private String productname;
     private String manufacturer;
     private String vendornameid;
     private String code;
     private String startdate;
     private String enddate;
     private String currencyid;
     private String unitprice;
     private Double unitpricenum;
     private String commisionrate;
     private String taxincurred;
     private String threshold;
     private String stockquantity;
     private String quantitylevel;
     private String quantityindemand;
     private String description;
//     private Date updatedon;
//     private Date createdon;
     private Long updatedOn;
     private Long createdOn;
     private boolean  isarchive;
     private boolean  syncaccounting;
     private int deleteflag;
     private String vendornamee;
     private String vendorphoneno;
     private String vendoremail;
     private Long startingdate;
     private Long endingdate;
     private int validflag;
     private String cellstyle;
     private CrmProductCustomData CrmProductCustomDataobj;

     private String companyid;
     public String getCompanyid() {
        return companyid;
    }

    public void setCompanyid(String companyid) {
        this.companyid = companyid;
    }

    public String getManufacturer() {
        return manufacturer;
    }

    public void setManufacturer(String manufacturer) {
        this.manufacturer = manufacturer;
    }

    public String getVendornameid() {
        return vendornameid;
    }

    public void setVendornameid(String vendornameid) {
        this.vendornameid = vendornameid;
    }


    public CrmProductCustomData getCrmProductCustomDataobj() {
        return CrmProductCustomDataobj;
    }

    public void setCrmProductCustomDataobj(CrmProductCustomData CrmProductCustomDataobj) {
        this.CrmProductCustomDataobj = CrmProductCustomDataobj;
    }

    public CrmProduct() {
    }


    public CrmProduct(String productid, User usersByUpdatedbyid, User usersByCreatedbyid, Company company, User usersByUserid, DefaultMasterItem crmCombodataByCategoryid, String productname, String code, String startdate, String enddate, String currencyid, String unitprice, String commisionrate, String taxincurred, String threshold, String stockquantity, String quantitylevel, String quantityindemand, String description, Long updatedOn, Long createdOn, boolean isarchive,boolean syncaccounting,int deleteflag, String vendornamee, String vendorphoneno, String vendoremail, Long startingdate, Long endingdate,int validflag) {
        this.productid = productid;
        this.usersByUpdatedbyid = usersByUpdatedbyid;
        this.usersByCreatedbyid = usersByCreatedbyid;
        this.company = company;
        this.usersByUserid = usersByUserid;
        this.crmCombodataByCategoryid = crmCombodataByCategoryid;
        this.productname = productname;
        this.code = code;
        this.startdate = startdate;
        this.enddate = enddate;
        this.currencyid = currencyid;
        this.unitprice = unitprice;
        this.commisionrate = commisionrate;
        this.taxincurred = taxincurred;
        this.threshold = threshold;
        this.stockquantity = stockquantity;
        this.quantitylevel = quantitylevel;
        this.quantityindemand = quantityindemand;
        this.description = description;
        this.updatedOn = updatedOn;
        this.createdOn = createdOn;
        this.isarchive = isarchive;
        this.syncaccounting = syncaccounting;
        this.deleteflag = deleteflag;
        this.vendornamee = vendornamee;
        this.vendorphoneno = vendorphoneno;
        this.vendoremail = vendoremail;
        this.startingdate = startingdate;
        this.endingdate = endingdate;
        this.validflag=validflag;
    }

    public String getProductcategoryID() {
        return productcategoryID;
    }

    public void setProductcategoryID(String productcategoryID) {
        this.productcategoryID = productcategoryID;
    }

    public String getProductid() {
        return this.productid;
    }

    public void setProductid(String productid) {
        this.productid = productid;
    }
    public User getUsersByUpdatedbyid() {
        return this.usersByUpdatedbyid;
    }

    public void setUsersByUpdatedbyid(User usersByUpdatedbyid) {
        this.usersByUpdatedbyid = usersByUpdatedbyid;
    }
    public User getUsersByCreatedbyid() {
        return this.usersByCreatedbyid;
    }

    public void setUsersByCreatedbyid(User usersByCreatedbyid) {
        this.usersByCreatedbyid = usersByCreatedbyid;
    }
    public Company getCompany() {
        return this.company;
    }

    public void setCompany(Company company) {
        this.company = company;
    }
    public User getUsersByUserid() {
        return this.usersByUserid;
    }

    public void setUsersByUserid(User usersByUserid) {
        this.usersByUserid = usersByUserid;
    }
    public DefaultMasterItem getCrmCombodataByCategoryid() {
        return this.crmCombodataByCategoryid;
    }

    public void setCrmCombodataByCategoryid(DefaultMasterItem crmCombodataByCategoryid) {
        this.crmCombodataByCategoryid = crmCombodataByCategoryid;
    }
    public String getProductname() {
        return this.productname;
    }

    public void setProductname(String productname) {
        this.productname = productname;
    }
    public String getCode() {
        return this.code;
    }

    public void setCode(String code) {
        this.code = code;
    }
    public String getStartdate() {
        return this.startdate;
    }

    public void setStartdate(String startdate) {
        this.startdate = startdate;
    }
    public String getEnddate() {
        return this.enddate;
    }

    public void setEnddate(String enddate) {
        this.enddate = enddate;
    }
    public String getCurrencyid() {
        return this.currencyid;
    }

    public void setCurrencyid(String currencyid) {
        this.currencyid = currencyid;
    }
    public String getUnitprice() {
        return this.unitprice;
    }

    public void setUnitprice(String unitprice) {
        this.unitprice = unitprice;
    }

    public Double getUnitpricenum() {
        try {
            return Double.parseDouble(this.getUnitprice());
        } catch(Exception ex) {
            return Double.parseDouble("0");
        }
    }

    public void setUnitpricenum(Double unitpricenum) {
        this.unitpricenum = unitpricenum;
    }
    
    public String getCommisionrate() {
        return this.commisionrate;
    }

    public void setCommisionrate(String commisionrate) {
        this.commisionrate = commisionrate;
    }
    public String getTaxincurred() {
        return this.taxincurred;
    }

    public void setTaxincurred(String taxincurred) {
        this.taxincurred = taxincurred;
    }
    public String getThreshold() {
        return this.threshold;
    }

    public void setThreshold(String threshold) {
        this.threshold = threshold;
    }
    public String getStockquantity() {
        return this.stockquantity;
    }

    public void setStockquantity(String stockquantity) {
        this.stockquantity = stockquantity;
    }
    public String getQuantitylevel() {
        return this.quantitylevel;
    }

    public void setQuantitylevel(String quantitylevel) {
        this.quantitylevel = quantitylevel;
    }
    public String getQuantityindemand() {
        return this.quantityindemand;
    }

    public void setQuantityindemand(String quantityindemand) {
        this.quantityindemand = quantityindemand;
    }
    public String getDescription() {
        return this.description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public Long getCreatedOn() {
        return createdOn;
    }

    public void setCreatedOn(Long createdOn) {
        this.createdOn = createdOn;
    }

    public Long getUpdatedOn() {
        return updatedOn;
    }

    public void setUpdatedOn(Long updatedOn) {
        this.updatedOn = updatedOn;
    }

    public Date getUpdatedon() {
        if(this.updatedOn!=null)
            return new Date(this.updatedOn);
        return null;
    }

    public void setUpdatedon(Date updatedon) {
        this.updatedOn = updatedon.getTime();
    }
    public Date getCreatedon() {
        if(this.createdOn!=null)
            return new Date(this.createdOn);
        return null;
    }

    public void setCreatedon(Date createdon) {
        this.createdOn = createdon.getTime();
    }
    
    public String getCreatedonGMT() {
        return StatUtil.DATE_FORMAT_GMT.format(getCreatedon());
    }

    public boolean getIsarchive() {
        return this.isarchive;
    }

    public void setIsarchive(boolean isarchive) {
        this.isarchive = isarchive;
    }

    public boolean isSyncaccounting() {
        return syncaccounting;
    }

    public void setSyncaccounting(boolean syncaccounting) {
        this.syncaccounting = syncaccounting;
    }

    public int getDeleteflag() {
        return this.deleteflag;
    }

    public void setDeleteflag(int deleteflag) {
        this.deleteflag = deleteflag;
    }

    public String getVendornamee() {
        return this.vendornamee;
    }

    public void setVendornamee(String vendornamee) {
        this.vendornamee = vendornamee;
    }
    public String getVendorphoneno() {
        return this.vendorphoneno;
    }

    public void setVendorphoneno(String vendorphoneno) {
        this.vendorphoneno = vendorphoneno;
    }

    public String getVendoremail() {
        return this.vendoremail;
    }

    public void setVendoremail(String vendoremail) {
        this.vendoremail = vendoremail;
    }
    public Long getStartingdate() {
        return this.startingdate;
    }

    public void setStartingdate(Long startingdate) {
        this.startingdate = startingdate;
    }

    public Long getEndingdate() {
        return this.endingdate;
    }

    public void setEndingdate(Long endingdate) {
        this.endingdate = endingdate;
    }
    public int getValidflag() {
        return this.validflag;
    }

    public void setValidflag(int validflag) {
        this.validflag = validflag;
    }

    public String getCellstyle() {
        return cellstyle;
    }

    public void setCellstyle(String cellstyle) {
        this.cellstyle = cellstyle;
    }

}
