/*
 * Copyright (C) 2012  Krawler Information Systems Pvt Ltd
 * All rights reserved.
 * 
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License
 * as published by the Free Software Foundation; either version 2
 * of the License, or (at your option) any later version.
 * 
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 * 
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
*/
package com.krawler.crm.database.tables;
// Generated Jul 9, 2009 7:57:07 PM by Hibernate Tools 3.2.1.GA

/**
 * CrmCombomaster generated by hbm2java
 */
public class CrmCombomaster  implements java.io.Serializable {


     private String masterid;
     private String comboname;
     private String parentid;
     
    public CrmCombomaster() {
    }


    public CrmCombomaster(String masterid) {
        this.masterid = masterid;
    }
    public CrmCombomaster(String masterid, String comboname, String parentid) {
       this.masterid = masterid;
       this.comboname = comboname;
       this.parentid = parentid;
    }

    public String getMasterid() {
        return this.masterid;
    }

    public void setMasterid(String masterid) {
        this.masterid = masterid;
    }
    public String getComboname() {
        return this.comboname;
    }

    public void setComboname(String comboname) {
        this.comboname = comboname;
    }
    public String getParentid() {
        return this.parentid;
    }

    public void setParentid(String parentid) {
        this.parentid = parentid;
    }
    


}


